[options]
admin_passwd = admin_master_password
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo_password

addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

proxy_mode = True
workers = 0
limit_time_cpu = 600
limit_time_real = 600
limit_request = 8192
max_cron_threads = 1

#comment testing webhook 2

