#!/usr/bin/env python3

import os
import ast

ADDONS_DIR = os.path.join(os.path.dirname(__file__), '..', 'custom_addons')
OUTPUT_FILE = os.path.join(os.path.dirname(__file__), '..', 'requirements.txt')


def extract_python_deps(manifest_path):
    with open(manifest_path, 'r') as f:
        content = f.read()
    try:
        manifest = ast.literal_eval(content)
        return manifest.get('external_dependencies', {}).get('python', [])
    except Exception as e:
        print(f"  WARNING: Could not parse {manifest_path}: {e}")
        return []


def main():
    # Check if custom_addons folder exists and has content
    if not os.path.exists(ADDONS_DIR) or not os.listdir(ADDONS_DIR):
        print("custom_addons folder is empty or missing — skipping requirements.txt generation.")
        return

    all_deps = set()

    for addon in sorted(os.listdir(ADDONS_DIR)):
        manifest_path = os.path.join(ADDONS_DIR, addon, '__manifest__.py')
        if not os.path.exists(manifest_path):
            continue
        deps = extract_python_deps(manifest_path)
        if deps:
            print(f"  {addon}: {deps}")
            all_deps.update(deps)

    if not all_deps:
        print("No external Python dependencies found.")
        return

    with open(OUTPUT_FILE, 'w') as f:
        f.write("# Auto-generated by generate_requirements.py\n")
        f.write("# Do not edit manually — run scripts/generate_requirements.py instead\n\n")
        for dep in sorted(all_deps):
            f.write(f"{dep}\n")

    print(f"\nWrote {len(all_deps)} package(s) to requirements.txt")


if __name__ == '__main__':
    main()
